name: Template Repository initialization
on:
  push:
    branches:
      - main
env:
  TEMPLATE_OWNER: idea2app
  TEMPLATE_NAME: Next-Bootstrap-ts

jobs:
  replace-repository-name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - if: github.repository != format('{0}/{1}', env.TEMPLATE_OWNER, env.TEMPLATE_NAME)
        run: |
          sh .github/workflows/replace-repository-name.sh \
            ${{ env.TEMPLATE_OWNER }} ${{ env.TEMPLATE_NAME }} \
            ${{ github.repository_owner }} ${{ github.event.repository.name }}
          rm -f .github/workflows/init-template.yml

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[fix] replace Repository Name'
